# Tile settings
TILE_WIDTH = 10
TILE_HEIGHT = 10

# Board settings
BOARD_ROWS = 64
BOARD_COLS = 64

# Window settings
WINDOW_WIDTH = BOARD_COLS * TILE_WIDTH
WINDOW_HEIGHT = BOARD_ROWS * TILE_HEIGHT
WINDOW_TITLE = "Pathfinder"
